### ISSUE TITLE
esr and rhat when NA in vector/matrix

### ISSUE THREAD

**Issue by audrey-b** [poissonconsulting/mcmcr#40]
When monitoring a vector that purposely contains NA's, mcmcr::esr throws an error and mcmcr::rhat returns NA. It would be desirable for esr and rhat to be calculated over the non-NA nodes.

See code below:

code = "N[2] ~ dbin(1-phi, N.1)
for(t in 3:K){
N[t] ~ dbin(1-phi, N[t-1])
}

Y[1] ~ dnorm(N.1, 1/sigma^2)
for(t in 2:K){
Y[t] ~ dnorm(N[t], 1/sigma^2)
}

sigma2 <- sigma^2
"

sims <- sims::sims_simulate(code=code,
                            constants=nlist(K=4),
                            parameters=nlist(phi=0.95, 
                                             N.1=100,
                                             sigma=5),
                            latent=NA, stochastic = NA, monitor=c("Y")
)

model <- jags.model(textConnection(
  paste0("model{ ", 
         code, 
         "phi ~ dunif(0,1) \n sigma ~ dunif(0,20) \n N.1 ~ dpois(100)}")), 
  data=list(Y=sims[[1]]$Y, K=sims[[1]]$K))

res <- jags.samples(model, variable.names="N", n.iter=200)
res <- mcmcr::as.mcmcr(res)

res

mcmcr::esr(res)
mcmcr::rhat(res)

**Comment by joethorley** [comment]
Will do when I have moment.
I'm thinking it makes sense to add na.rm = FALSE as a default argument.
