### ISSUE TITLE
ESS is different for different OS when parameter is fixed

### ISSUE THREAD

**Issue by sebdalgarno** [poissonconsulting/mcmcr#58]
this was causing a test in bboutools to fail for all but windows in actions cmd-check
on windows and locally, ESS of fixed parameter is 3
on macOS-latest and other ubuntu releases, ESS is 3000

I think the underlying issue occurs in .esr_numeric, where the output of this will change

```
x <- bboutools:::fit_recruitment$samples[[1]]
.esr_numeric(x[,,1][1,], na_rm = FALSE)
```
in this case the fit_recruitment object has adult_female_proportion parameter fixed at 0.65 and fit_recruitment$samples[[1]] contains the samples for adult_female_proportion (all 0.65)

the esr output of above for me locally is 0.001  but will be 1 on macOS-latest

**Comment by joethorley** [comment]
@sebdalgarno - I've fixed on main branch
